In [2]:
import numpy as np
a=np.zeros(3,dtype=int)
print(a)

[0 0 0]


In [3]:
a=np.ones(5,dtype=int)
print(a)

[1 1 1 1 1]


In [4]:
a=np.array([1,2,3,4,5])
for i in a:
    print(i)

1
2
3
4
5


In [6]:
array=[]
a=int(input("enter the size"))
for i in range(a):
    array.append(input("enter the values"))
print(array)

enter the size3
enter the values1
enter the values2
enter the values3
['1', '2', '3']


In [7]:
import collections
x=np.array([1,2,3,4,5,1,2,1,9,1])
print("Original array:")
counter=collections.Counter(x)
print(counter)

Original array:
Counter({1: 4, 2: 2, 3: 1, 4: 1, 5: 1, 9: 1})


In [8]:
a=np.array([1,2,3,4,5,1,2,1,9,1])
print("numpy array:")
print(a)
c=np.count_nonzero(a==1)
print(c)

numpy array:
[1 2 3 4 5 1 2 1 9 1]
4


In [9]:
a=np.array([1,2,3,4,5])
print(6 in x)

False


In [11]:
a=np.array([1,2,3,4,5])
print(min(a))
print(max(a))

1
5
